-- SQL Migration: Create app_requests table
CREATE TABLE IF NOT EXISTS app_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE app_requests ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (unauthenticated submissions)
CREATE POLICY "Allow anonymous inserts to app_requests" ON app_requests
  FOR INSERT WITH CHECK (true);
